/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twilight;

import java.util.Random;

/**
 *
 * @author Jayde
 */
public class NewGamePanel extends javax.swing.JPanel {
    
    final private Random random = new Random();
    int player1_element = Game.UNKNOWN_ELEMENT, 
        player2_element = Game.UNKNOWN_ELEMENT;

    /**
     * Creates new form NewGamePanel
     */
    public NewGamePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        player1_elementButtonGroup = new javax.swing.ButtonGroup();
        player2_elementButtonGroup = new javax.swing.ButtonGroup();
        newGameLabel = new javax.swing.JLabel();
        player1_NamePanel = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();
        elementLabel = new javax.swing.JLabel();
        player1_NameTextField = new javax.swing.JTextField();
        player1_ElementPanel = new javax.swing.JPanel();
        fireRB_1 = new javax.swing.JRadioButton();
        waterRB_1 = new javax.swing.JRadioButton();
        windRB_1 = new javax.swing.JRadioButton();
        earthRB_1 = new javax.swing.JRadioButton();
        blank_1 = new javax.swing.JPanel();
        lightningRB_1 = new javax.swing.JRadioButton();
        iceRB_1 = new javax.swing.JRadioButton();
        natureRB_1 = new javax.swing.JRadioButton();
        metalRB_1 = new javax.swing.JRadioButton();
        blank_2 = new javax.swing.JPanel();
        ailmentRB_1 = new javax.swing.JRadioButton();
        unknownRB_1 = new javax.swing.JRadioButton();
        barrierRB_1 = new javax.swing.JRadioButton();
        animalRB_1 = new javax.swing.JRadioButton();
        blank_3 = new javax.swing.JPanel();
        summonRB_1 = new javax.swing.JRadioButton();
        mirrorRB_1 = new javax.swing.JRadioButton();
        timeRB_1 = new javax.swing.JRadioButton();
        spaceRB_1 = new javax.swing.JRadioButton();
        randomRB_1 = new javax.swing.JRadioButton();
        player2_NamePanel = new javax.swing.JPanel();
        elementLabel1 = new javax.swing.JLabel();
        player2_NameTextField = new javax.swing.JTextField();
        player_2elementPanel = new javax.swing.JPanel();
        fireRB_2 = new javax.swing.JRadioButton();
        waterRB_2 = new javax.swing.JRadioButton();
        windRB_2 = new javax.swing.JRadioButton();
        earthRB_2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        lightningRB_2 = new javax.swing.JRadioButton();
        iceRB_2 = new javax.swing.JRadioButton();
        natureRB_2 = new javax.swing.JRadioButton();
        metalRB_2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        ailmentRB_2 = new javax.swing.JRadioButton();
        unknownRB_2 = new javax.swing.JRadioButton();
        barrierRB_2 = new javax.swing.JRadioButton();
        animalRB_2 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        summonRB_2 = new javax.swing.JRadioButton();
        mirrorRB_2 = new javax.swing.JRadioButton();
        timeRB_2 = new javax.swing.JRadioButton();
        spaceRB_2 = new javax.swing.JRadioButton();
        randomRB_2 = new javax.swing.JRadioButton();
        confirmationPanel = new javax.swing.JPanel();
        confirmationLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.GridLayout(6, 1));

        newGameLabel.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        newGameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newGameLabel.setText("New Game!");
        add(newGameLabel);

        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setText("Choose each player's elements.");

        elementLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elementLabel.setText("'s Element");

        player1_NameTextField.setBackground(new java.awt.Color(240, 240, 240));
        player1_NameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        player1_NameTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        player1_NameTextField.setText("Player");
        player1_NameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        player1_NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1_NameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout player1_NamePanelLayout = new javax.swing.GroupLayout(player1_NamePanel);
        player1_NamePanel.setLayout(player1_NamePanelLayout);
        player1_NamePanelLayout.setHorizontalGroup(
            player1_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1_NamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player1_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                    .addGroup(player1_NamePanelLayout.createSequentialGroup()
                        .addComponent(player1_NameTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elementLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        player1_NamePanelLayout.setVerticalGroup(
            player1_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1_NamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(player1_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(elementLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player1_NameTextField))
                .addContainerGap())
        );

        add(player1_NamePanel);

        player1_ElementPanel.setLayout(new java.awt.GridLayout(4, 5));

        player1_elementButtonGroup.add(fireRB_1);
        fireRB_1.setText("Fire");
        player1_ElementPanel.add(fireRB_1);

        player1_elementButtonGroup.add(waterRB_1);
        waterRB_1.setText("Water");
        player1_ElementPanel.add(waterRB_1);

        player1_elementButtonGroup.add(windRB_1);
        windRB_1.setText("Wind");
        player1_ElementPanel.add(windRB_1);

        player1_elementButtonGroup.add(earthRB_1);
        earthRB_1.setText("Earth");
        player1_ElementPanel.add(earthRB_1);

        javax.swing.GroupLayout blank_1Layout = new javax.swing.GroupLayout(blank_1);
        blank_1.setLayout(blank_1Layout);
        blank_1Layout.setHorizontalGroup(
            blank_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        blank_1Layout.setVerticalGroup(
            blank_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        player1_ElementPanel.add(blank_1);

        player1_elementButtonGroup.add(lightningRB_1);
        lightningRB_1.setText("Lightning");
        player1_ElementPanel.add(lightningRB_1);

        player1_elementButtonGroup.add(iceRB_1);
        iceRB_1.setText("Ice");
        player1_ElementPanel.add(iceRB_1);

        player1_elementButtonGroup.add(natureRB_1);
        natureRB_1.setText("Nature");
        player1_ElementPanel.add(natureRB_1);

        player1_elementButtonGroup.add(metalRB_1);
        metalRB_1.setText("Metal");
        player1_ElementPanel.add(metalRB_1);

        javax.swing.GroupLayout blank_2Layout = new javax.swing.GroupLayout(blank_2);
        blank_2.setLayout(blank_2Layout);
        blank_2Layout.setHorizontalGroup(
            blank_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        blank_2Layout.setVerticalGroup(
            blank_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        player1_ElementPanel.add(blank_2);

        player1_elementButtonGroup.add(ailmentRB_1);
        ailmentRB_1.setText("Ailment");
        player1_ElementPanel.add(ailmentRB_1);

        player1_elementButtonGroup.add(unknownRB_1);
        unknownRB_1.setText("<Unknown>");
        unknownRB_1.setEnabled(false);
        unknownRB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unknownRB_1ActionPerformed(evt);
            }
        });
        player1_ElementPanel.add(unknownRB_1);

        player1_elementButtonGroup.add(barrierRB_1);
        barrierRB_1.setText("Barrier");
        player1_ElementPanel.add(barrierRB_1);

        player1_elementButtonGroup.add(animalRB_1);
        animalRB_1.setText("Animal");
        player1_ElementPanel.add(animalRB_1);

        javax.swing.GroupLayout blank_3Layout = new javax.swing.GroupLayout(blank_3);
        blank_3.setLayout(blank_3Layout);
        blank_3Layout.setHorizontalGroup(
            blank_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        blank_3Layout.setVerticalGroup(
            blank_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        player1_ElementPanel.add(blank_3);

        player1_elementButtonGroup.add(summonRB_1);
        summonRB_1.setText("Summon");
        player1_ElementPanel.add(summonRB_1);

        player1_elementButtonGroup.add(mirrorRB_1);
        mirrorRB_1.setText("Mirror");
        player1_ElementPanel.add(mirrorRB_1);

        player1_elementButtonGroup.add(timeRB_1);
        timeRB_1.setText("Time");
        player1_ElementPanel.add(timeRB_1);

        player1_elementButtonGroup.add(spaceRB_1);
        spaceRB_1.setText("Space");
        player1_ElementPanel.add(spaceRB_1);

        player1_elementButtonGroup.add(randomRB_1);
        randomRB_1.setText("<Random>");
        randomRB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomRB_1ActionPerformed(evt);
            }
        });
        player1_ElementPanel.add(randomRB_1);

        add(player1_ElementPanel);

        elementLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elementLabel1.setText("'s Element");

        player2_NameTextField.setEditable(false);
        player2_NameTextField.setBackground(new java.awt.Color(240, 240, 240));
        player2_NameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        player2_NameTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        player2_NameTextField.setText("Opponent");
        player2_NameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        player2_NameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        player2_NameTextField.setHighlighter(null);
        player2_NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2_NameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout player2_NamePanelLayout = new javax.swing.GroupLayout(player2_NamePanel);
        player2_NamePanel.setLayout(player2_NamePanelLayout);
        player2_NamePanelLayout.setHorizontalGroup(
            player2_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2_NamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(player2_NameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elementLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );
        player2_NamePanelLayout.setVerticalGroup(
            player2_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2_NamePanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(player2_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(elementLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player2_NameTextField))
                .addContainerGap())
        );

        add(player2_NamePanel);

        player_2elementPanel.setLayout(new java.awt.GridLayout(4, 5));

        player2_elementButtonGroup.add(fireRB_2);
        fireRB_2.setText("Fire");
        player_2elementPanel.add(fireRB_2);

        player2_elementButtonGroup.add(waterRB_2);
        waterRB_2.setText("Water");
        player_2elementPanel.add(waterRB_2);

        player2_elementButtonGroup.add(windRB_2);
        windRB_2.setText("Wind");
        player_2elementPanel.add(windRB_2);

        player2_elementButtonGroup.add(earthRB_2);
        earthRB_2.setText("Earth");
        player_2elementPanel.add(earthRB_2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        player_2elementPanel.add(jPanel1);

        player2_elementButtonGroup.add(lightningRB_2);
        lightningRB_2.setText("Lightning");
        player_2elementPanel.add(lightningRB_2);

        player2_elementButtonGroup.add(iceRB_2);
        iceRB_2.setText("Ice");
        player_2elementPanel.add(iceRB_2);

        player2_elementButtonGroup.add(natureRB_2);
        natureRB_2.setText("Nature");
        player_2elementPanel.add(natureRB_2);

        player2_elementButtonGroup.add(metalRB_2);
        metalRB_2.setText("Metal");
        player_2elementPanel.add(metalRB_2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        player_2elementPanel.add(jPanel3);

        player2_elementButtonGroup.add(ailmentRB_2);
        ailmentRB_2.setText("Ailment");
        player_2elementPanel.add(ailmentRB_2);

        player2_elementButtonGroup.add(unknownRB_2);
        unknownRB_2.setText("<Unknown>");
        unknownRB_2.setEnabled(false);
        player_2elementPanel.add(unknownRB_2);

        player2_elementButtonGroup.add(barrierRB_2);
        barrierRB_2.setText("Barrier");
        player_2elementPanel.add(barrierRB_2);

        player2_elementButtonGroup.add(animalRB_2);
        animalRB_2.setText("Animal");
        player_2elementPanel.add(animalRB_2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        player_2elementPanel.add(jPanel4);

        player2_elementButtonGroup.add(summonRB_2);
        summonRB_2.setText("Summon");
        player_2elementPanel.add(summonRB_2);

        player2_elementButtonGroup.add(mirrorRB_2);
        mirrorRB_2.setText("Mirror");
        player_2elementPanel.add(mirrorRB_2);

        player2_elementButtonGroup.add(timeRB_2);
        timeRB_2.setText("Time");
        player_2elementPanel.add(timeRB_2);

        player2_elementButtonGroup.add(spaceRB_2);
        spaceRB_2.setText("Space");
        player_2elementPanel.add(spaceRB_2);

        player2_elementButtonGroup.add(randomRB_2);
        randomRB_2.setText("<Random>");
        randomRB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomRB_2ActionPerformed(evt);
            }
        });
        player_2elementPanel.add(randomRB_2);

        add(player_2elementPanel);

        confirmationPanel.setLayout(new java.awt.BorderLayout());

        confirmationLabel.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        confirmationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmationLabel.setText("< > vs. < >");
        confirmationPanel.add(confirmationLabel, java.awt.BorderLayout.CENTER);

        nextButton.setText("Next >>");
        nextButton.setEnabled(false);
        confirmationPanel.add(nextButton, java.awt.BorderLayout.LINE_END);

        add(confirmationPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void player1_NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player1_NameTextFieldActionPerformed

    private void player2_NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player2_NameTextFieldActionPerformed

    private void unknownRB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unknownRB_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unknownRB_1ActionPerformed

    private void randomRB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomRB_1ActionPerformed
        int i = random.nextInt(16)+1;
        switch(i){
            case  1: player1_element = Game.FIRE_ELEMENT;      break;
            case  2: player1_element = Game.WATER_ELEMENT;     break;
            case  3: player1_element = Game.WIND_ELEMENT;      break;     
            case  4: player1_element = Game.EARTH_ELEMENT;     break;
            case  5: player1_element = Game.LIGHTNING_ELEMENT; break;
            case  6: player1_element = Game.ICE_ELEMENT;       break;
            case  7: player1_element = Game.NATURE_ELEMENT;    break;     
            case  8: player1_element = Game.METAL_ELEMENT;     break;
            case  9: player1_element = Game.AILMENT_ELEMENT;   break;
            case 10: player1_element = Game.XXX_ELEMENT;       break;
            case 11: player1_element = Game.BARRIER_ELEMENT;   break;     
            case 12: player1_element = Game.ANIMAL_ELEMENT;    break;
            case 13: player1_element = Game.SUMMON_ELEMENT;    break;
            case 14: player1_element = Game.MIRROR_ELEMENT;    break;
            case 15: player1_element = Game.TIME_ELEMENT;      break;     
            case 16: player1_element = Game.SPACE_ELEMENT;     break;
        }
        updateConfirmationPanel();
                
    }//GEN-LAST:event_randomRB_1ActionPerformed

    private void randomRB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomRB_2ActionPerformed
        int i = random.nextInt(16)+1;
        switch(i){
            case  1: player2_element = Game.FIRE_ELEMENT;      break;
            case  2: player2_element = Game.WATER_ELEMENT;     break;
            case  3: player2_element = Game.WIND_ELEMENT;      break;     
            case  4: player2_element = Game.EARTH_ELEMENT;     break;
            case  5: player2_element = Game.LIGHTNING_ELEMENT; break;
            case  6: player2_element = Game.ICE_ELEMENT;       break;
            case  7: player2_element = Game.NATURE_ELEMENT;    break;     
            case  8: player2_element = Game.METAL_ELEMENT;     break;
            case  9: player2_element = Game.AILMENT_ELEMENT;   break;
            case 10: player2_element = Game.XXX_ELEMENT;       break;
            case 11: player2_element = Game.BARRIER_ELEMENT;   break;     
            case 12: player2_element = Game.ANIMAL_ELEMENT;    break;
            case 13: player2_element = Game.SUMMON_ELEMENT;    break;
            case 14: player2_element = Game.MIRROR_ELEMENT;    break;
            case 15: player2_element = Game.TIME_ELEMENT;      break;     
            case 16: player2_element = Game.SPACE_ELEMENT;     break;
        }
        updateConfirmationPanel();
    }//GEN-LAST:event_randomRB_2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ailmentRB_1;
    private javax.swing.JRadioButton ailmentRB_2;
    private javax.swing.JRadioButton animalRB_1;
    private javax.swing.JRadioButton animalRB_2;
    private javax.swing.JRadioButton barrierRB_1;
    private javax.swing.JRadioButton barrierRB_2;
    private javax.swing.JPanel blank_1;
    private javax.swing.JPanel blank_2;
    private javax.swing.JPanel blank_3;
    private javax.swing.JLabel confirmationLabel;
    private javax.swing.JPanel confirmationPanel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JRadioButton earthRB_1;
    private javax.swing.JRadioButton earthRB_2;
    private javax.swing.JLabel elementLabel;
    private javax.swing.JLabel elementLabel1;
    private javax.swing.JRadioButton fireRB_1;
    private javax.swing.JRadioButton fireRB_2;
    private javax.swing.JRadioButton iceRB_1;
    private javax.swing.JRadioButton iceRB_2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton lightningRB_1;
    private javax.swing.JRadioButton lightningRB_2;
    private javax.swing.JRadioButton metalRB_1;
    private javax.swing.JRadioButton metalRB_2;
    private javax.swing.JRadioButton mirrorRB_1;
    private javax.swing.JRadioButton mirrorRB_2;
    private javax.swing.JRadioButton natureRB_1;
    private javax.swing.JRadioButton natureRB_2;
    private javax.swing.JLabel newGameLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JPanel player1_ElementPanel;
    private javax.swing.JPanel player1_NamePanel;
    private javax.swing.JTextField player1_NameTextField;
    private javax.swing.ButtonGroup player1_elementButtonGroup;
    private javax.swing.JPanel player2_NamePanel;
    private javax.swing.JTextField player2_NameTextField;
    private javax.swing.ButtonGroup player2_elementButtonGroup;
    private javax.swing.JPanel player_2elementPanel;
    private javax.swing.JRadioButton randomRB_1;
    private javax.swing.JRadioButton randomRB_2;
    private javax.swing.JRadioButton spaceRB_1;
    private javax.swing.JRadioButton spaceRB_2;
    private javax.swing.JRadioButton summonRB_1;
    private javax.swing.JRadioButton summonRB_2;
    private javax.swing.JRadioButton timeRB_1;
    private javax.swing.JRadioButton timeRB_2;
    private javax.swing.JRadioButton unknownRB_1;
    private javax.swing.JRadioButton unknownRB_2;
    private javax.swing.JRadioButton waterRB_1;
    private javax.swing.JRadioButton waterRB_2;
    private javax.swing.JRadioButton windRB_1;
    private javax.swing.JRadioButton windRB_2;
    // End of variables declaration//GEN-END:variables

    private void updateConfirmationPanel() {
        boolean ready = true;
        confirmationLabel.setText("");
        if(Game.getElementName(player1_element) == null){ //if player1 not set
            confirmationLabel.setText(confirmationLabel.getText().concat("< >"));
            ready = false;
        }
        else
            confirmationLabel.setText(confirmationLabel.getText().concat(Game.getElementName(player1_element)));
        confirmationLabel.setText(confirmationLabel.getText().concat(" vs. "));
        if(Game.getElementName(player2_element) == null){ //if player2 not set
            confirmationLabel.setText(confirmationLabel.getText().concat("< >"));
            ready = false;
        }
        else
            confirmationLabel.setText(confirmationLabel.getText().concat(Game.getElementName(player2_element)));
        nextButton.setEnabled(ready);
    }
}

